export default {
  1: 'Acqua, bibite & succhi',
  2: 'Pastine',
  3: 'Caffè',
  4: 'Pasta e sughi',
  5: "Sott'olio",
  6: 'Pirofile e pellicole',
  7: 'Cucina',
  8: 'Prodotti per igene della casa',
  9: 'Bucato',
  10: 'Igene personale',
  11: 'Salumi e formaggi',
  12: 'Colazione',
  13: 'Pizze, gelati e surgelati',
  14: 'Pesce',
  15: 'Carne',
  16: 'Frutta e verdura',
  17: 'Altro',
};
